version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: build/Dockerfile
      args:
        USER: '${USER}'
        USER_ID: '${USER_ID}'
        USER_GROUP: '${USER_GROUP}'
    image: bric_app
    container_name: bric_app
    command: bash -c "start-container"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:8.0
    container_name: bric_mysql
    restart: unless-stopped
    env_file:
        - build/development.env
    volumes:
      - bric_db:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: bric_nginx
    restart: unless-stopped
    ports:
        - '80:80'
    volumes:
      - ./:/var/www
      - ./build/nginx:/etc/nginx/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    container_name: bric_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  bric_db:
